# STA160 Data Science 2021 Spring

# Part2- Python Numpy

In [1]:
import numpy as np

### Numpy Array

In [2]:
a = np.array([1, 2, 3])
print(a)               
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [4]:
np.array([[1, 2, 3], [3, 4, 5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
np.array([[1], [2], [3]])

array([[1],
       [2],
       [3]])

In [6]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [7]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The elements of Numpy Array must have the same data type. It's different with List !

In [8]:
np.array([1,2.,3])

array([1., 2., 3.])

In [9]:
np.array([1,2,'3'])

array(['1', '2', '3'], dtype='<U21')

### shape and reshape

In [10]:
a=np.array([1, 2, 3])
a.shape

(3,)

In [11]:
b=np.array([[1, 2, 3], [3, 4, 5]])
b.shape

(2, 3)

In [12]:
c=np.array([[1],[2],[3]])
c.shape

(3, 1)

In [13]:
d=np.array([[1,2,3]])
d.shape

(1, 3)

In [14]:
e=np.array([1, 2, 3, 4])
e.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [15]:
e.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [16]:
e.reshape(1,4)

array([[1, 2, 3, 4]])

In [17]:
f=np.random.random((2, 3, 4))
f

array([[[0.22945736, 0.32709332, 0.95064369, 0.49869325],
        [0.52720788, 0.05658525, 0.08253308, 0.78495571],
        [0.19494169, 0.06799886, 0.39313777, 0.71276597]],

       [[0.03657584, 0.98833205, 0.91324566, 0.97162003],
        [0.84471161, 0.04085217, 0.80676789, 0.52470186],
        [0.42077787, 0.1725874 , 0.49210466, 0.2960201 ]]])

In [18]:
print(f.shape)
print(f.ndim)
print(f.size)

(2, 3, 4)
3
24


Broadcasting

In [19]:
f[:, np.newaxis, :].shape

(2, 1, 3, 4)

In [20]:
a=np.array([1,2,3])
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

### initialization

In [21]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.76865296, 0.7392164 , 0.79632473],
       [0.88631696, 0.35768436, 0.46243294],
       [0.92209896, 0.77834702, 0.27316941]])

In [25]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 1, 4],
       [7, 7, 7],
       [6, 3, 0]])

In [26]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.05991595, -0.05857757, -1.45978109],
       [ 2.31729379, -1.44544943, -1.22808807],
       [-0.72626641,  1.55433465,  0.68875604]])

### basic operations

In [27]:
x = np.array([-2,-1,0,1,2])
print("x     =", x)
print("x + 2 =", x + 2)
print("x - 2 =", x - 2)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x //2 =", x // 2) # Floor division
print("x % 2 = ", x % 2) # Modulus - remainder of the division of left operand by the right
print("x^2   = ", x**2)
print("|x|   = ", abs(x))
print("e^x   =", np.exp(x))
print("x mean   =", np.mean(x))
print("x std    =", np.std(x))
print("x median =", np.median(x))

x     = [-2 -1  0  1  2]
x + 2 = [0 1 2 3 4]
x - 2 = [-4 -3 -2 -1  0]
x * 2 = [-4 -2  0  2  4]
x / 2 = [-1.  -0.5  0.   0.5  1. ]
x //2 = [-1 -1  0  0  1]
x % 2 =  [0 1 0 1 0]
x^2   =  [4 1 0 1 4]
|x|   =  [2 1 0 1 2]
e^x   = [0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
x mean   = 0.0
x std    = 1.4142135623730951
x median = 0.0


In [28]:
# is there any value less than 0?
np.any(x < 0)

True

In [29]:
# are all values less than 0?
np.all(x < 0)

False

In [30]:
# sum of all array elements; sum(x) or x.sum(); cumulative sum: np.cumsum
np.add.reduce(x)

0

In [31]:
# product of all array elements;  cumulative product: np.cumprod
np.multiply.reduce(x)

0

In [32]:
# Test whether each element of a 1-D array is also present in a second array.
np.in1d([1,2,3],[2,4,5,6,7])

array([False,  True, False])

In [33]:
[i in [2,4,5,6,7] for i in [1,2,3]]

[False, True, False]

In [34]:
# intersection of two arrays
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [35]:
# union of two arrays
np.union1d([-1, 0, 1], [-2, 0, 2])

array([-2, -1,  0,  1,  2])

To intersect more than two arrays, use functools.reduce()

It can apply a function of two arguments cumulatively to the items of a sequence from left to right.

In [36]:
from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])

### matrix operations

In [37]:
M=np.array([[1,0.5,0.3],[0.5,1,0.5],[0.3,0.5,1]])
M

array([[1. , 0.5, 0.3],
       [0.5, 1. , 0.5],
       [0.3, 0.5, 1. ]])

In [38]:
M.T

array([[1. , 0.5, 0.3],
       [0.5, 1. , 0.5],
       [0.3, 0.5, 1. ]])

In [39]:
# diagonal array
np.diag(M)

array([1., 1., 1.])

In [40]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [41]:
# trace
np.trace(M)

3.0

In [42]:
# Compute the inverse of a matrix.
np.linalg.inv(M)

array([[ 1.33928571, -0.625     , -0.08928571],
       [-0.625     ,  1.625     , -0.625     ],
       [-0.08928571, -0.625     ,  1.33928571]])

In [43]:
# determinant
np.linalg.det(M)

0.56

In [44]:
# eigenvalues and right eigenvectors of a square array
np.linalg.eig(M)

(array([1.87284161, 0.7       , 0.42715839]),
 array([[-5.49434787e-01, -7.07106781e-01,  4.45108319e-01],
        [-6.29478221e-01, -1.29493854e-16, -7.77018127e-01],
        [-5.49434787e-01,  7.07106781e-01,  4.45108319e-01]]))

In [45]:
# Singular Value Decomposition
u,D,vh = np.linalg.svd(M)

In [46]:
u @ np.diag(D) @ vh

array([[1. , 0.5, 0.3],
       [0.5, 1. , 0.5],
       [0.3, 0.5, 1. ]])

In [47]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
grid.sum(axis=1)

array([ 6, 15])

In [49]:
grid.max(axis=0)

array([4, 5, 6])

In [50]:
grid.argmin(axis=0) # Return indices of the minimum values along the given axis

array([0, 0, 0])

In [51]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### selection and slicing

In [53]:
m=np.arange(1,10).reshape((3, 3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
m[0]

array([1, 2, 3])

In [55]:
m[0,1] # the first row and the second column

2

In [56]:
m[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [57]:
m[:,1]

array([2, 5, 8])

In [58]:
m[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [59]:
m[1:3,[0,2]]

array([[4, 6],
       [7, 9]])

In [60]:
m[[[1], [2]], [0, 2]] 

array([[4, 6],
       [7, 9]])

In [61]:
m[[1, 2], [[0], [2]]] # transpose of previous one

array([[4, 7],
       [6, 9]])

In [62]:
print(m)
m[(m<5) & (m>2)]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 4])

In [63]:
m[(m<2) | (m>5)]

array([1, 6, 7, 8, 9])

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [64]:
m=np.arange(1,10).reshape((3, 3))
print(m)
sub_m=m[0:2,0:2]
sub_m[0,0]=100
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [65]:
a=[1,2,3,4]
a_sub=a[1:3]
a_sub[0]=-1
print('a_sub:',a_sub)
print('a:',a)

a_sub: [-1, 3]
a: [1, 2, 3, 4]


In [66]:
m=np.arange(1,10).reshape((3, 3))
print(m)
sub_m=m[0:2,0:2].copy()
sub_m[0,0]=100
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
